#!/usr/bin/env python
# encoding: utf-8
'''
pbldr -- An arch linux packaging tool.

Copyright (c) 2013, Jesus Alvarez <jeezusjr@gmail.com>
License: MIT (See LICENSE for details)
'''

import sys
import argparse

import app
import logger
from logger import log

logr = logger.getLogger(__name__)

aname = logger.colorize('pbldr -- Magically build and add packages to an Arch '
                        'Linux package repository.', 'yellow', 'bgcyan',
                        'bold')

intro = '\n' + aname

usage = intro + '''

Usage: pbldr [OPTIONS]

Commands:

build   Build the selected packages and sources. ALL packages by default.

source  Build the source of the package. This does not need to be specified if
        using the 'build' command.

repo    Add selected packages to the projects repositories.

Optional arguments for all commands:
-h, --help          Show this help message and exit.
-p PKG, -p N        Select packages to use.

Optional arguments for the 'build' command:
-r  Select chroot root path. Example "/opt/chroot".
-l  Select chroot copy name. Example "anet".
-c  Clean chroot before building.

Optional arguments for the 'source' command:
NONE

Optional arguments for the 'repo' command:
NONE'''

# Parse the arguments!
parser = argparse.ArgumentParser(add_help=False)
parser.add_argument('-h', '--help', action='store_true', default=False)
parser.add_argument('-p', action='append', metavar='pkg')
subparser = parser.add_subparsers(dest='subparser_name')

build_parser = subparser.add_parser('build')
build_parser.add_argument('-r', nargs='?')
build_parser.add_argument('-l', nargs='?')
build_parser.add_argument('-c', action='store_true', default=False)

subparser.add_parser('repo')

subparser.add_parser('source')

args = parser.parse_args()

if len(sys.argv) == 1 or args.help:
    print(usage)
    sys.exit(1)

if __name__ == '__main__':
    try:
        app.App(args)
        log('All done')
    except (KeyboardInterrupt, EOFError):
        log('\nToodles')
